DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS guitars CASCADE;
DROP TABLE IF EXISTS user_favorites CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE guitars (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  type VARCHAR(255) NOT NULL,
  img_url VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE user_favorites (
  id SERIAL PRIMARY KEY NOT NULL,

  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  guitar_id INTEGER REFERENCES guitars(id) ON DELETE CASCADE
);
